services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sila-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/webapp
      dockerfile: Dockerfile
    container_name: sila-frontend
    ports:
      - "8080:80"   # nginx serve build pronto
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: sila-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sila_dev
    ports:
      - "5432:5432"
    volumes:
      - sila_db_data:/var/lib/postgresql/data

volumes:
  sila_db_data: