version: '3.8'

services:
  test-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Truman1_Marcelo1_1985
      POSTGRES_DB: test_sila
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  test-mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8025"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      test-db:
        condition: service_healthy
      test-mailhog:
        condition: service_healthy
    environment:
      - TEST_DATABASE_URL=postgresql://postgres:Truman1_Marcelo1_1985@test-db:5432/test_sila
      - SMTP_HOST=test-mailhog
      - SMTP_PORT=1025
      - SMTP_USER=postgres
      - SMTP_PASSWORD=Truman1_Marcelo1_1985
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        python -m pytest -v --cov=app --cov-report=xml:reports/coverage.xml \
        --junitxml=reports/junit.xml tests/
      "

volumes:
  postgres_test_data:
