"""Test migration with drop_table statements

Revision ID: test123
Revises: 
Create Date: 2025-08-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
 
    # Tables dropped in dependency order (auto-generated)
    op.drop_table('Inscricao')
    op.drop_table('Payment')
    op.drop_table('PaymentNotification')
   # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
