global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'sila-production'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # SILA System Application Metrics
  - job_name: 'sila-system'
    static_configs:
      - targets: ['host.docker.internal:8001']  # SILA metrics endpoint
    scrape_interval: 30s
    metrics_path: '/monitoring/metrics/prometheus'
    scrape_timeout: 10s
    honor_labels: true

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Cadvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # AlertManager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # PostgreSQL Database metrics (if pg_exporter is used)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['host.docker.internal:9187']  # pg_exporter port
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is used)
  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121']  # redis_exporter port
    scrape_interval: 30s

  # BlackBox Exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://host.docker.internal:8000/monitoring/health/
        - http://host.docker.internal:8000/api/v1/health/agendamento-consulta
        - http://host.docker.internal:8000/api/v1/citizenship/carteira-identidade
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    
# Remote write configuration (optional - for long-term storage)
# remote_write:
#   - url: "http://cortex:9009/api/prom/push"
#     queue_config:
#       max_samples_per_send: 1000
#       batch_send_deadline: 5s
#       max_shards: 200