# test-migration.ps1
# Creates a test migration file for testing the fix-migration-order script

$testMigrationContent = @"
"""Test migration

Revision ID: test123
Revises: 
Create Date: 2025-08-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PaymentNotification')  # Depends on Payment
    op.drop_table('Payment')  # Should be dropped after PaymentNotification
    op.drop_table('Inscricao')  # No dependencies
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
"@

# Create test migration file
$testFile = ".\test_migration.py"
$testContent | Out-File -FilePath $testFile -Encoding utf8

Write-Host "✅ Created test migration file: $testFile"
Write-Host "Run the following command to test the fix-migration-order script:"
Write-Host "pwsh -File .\scripts\fix-migration-order.ps1 -MigrationFile \"$testFile\""
