apiVersion: 1

# Configurações de notificação
alertmanager_config:
  # Configuração do Alertmanager
  alertmanager:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

  # Configurações de templates para mensagens de alerta
  templates:
    - '/etc/grafana/provisioning/alerting/templates/*.tmpl'

  # Configuração de rotas de alerta
  route:
    group_by: ['alertname', 'severity']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    receiver: 'slack_receiver'
    routes:
      - receiver: 'critical_alerts'
        matchers:
          - severity=~"critical|warning"
      - receiver: 'warning_alerts'
        matchers:
          - severity="warning"

  # Configuração de destinatários
  receivers:
    - name: 'critical_alerts'
      slack_configs:
        - send_resolved: true
          title: '{{ template "slack.sila.title" . }}'
          text: '{{ template "slack.sila.text" . }}'
          http_config: {}
          api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
          channel: '#alerts-critical'
          icon_emoji: ':fire:'
          username: 'SILA Alert Manager'

    - name: 'warning_alerts'
      slack_configs:
        - send_resolved: true
          title: '{{ template "slack.sila.title" . }}'
          text: '{{ template "slack.sila.text" . }}'
          http_config: {}
          api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
          channel: '#alerts-warning'
          icon_emoji: ':warning:'
          username: 'SILA Alert Manager'

    - name: 'slack_receiver'
      slack_configs:
        - send_resolved: true
          title: '{{ template "slack.sila.title" . }}'
          text: '{{ template "slack.sila.text" . }}'
          http_config: {}
          api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
          channel: '#alerts-general'
          icon_emoji: ':bell:'
          username: 'SILA Alert Manager'

