apiVersion: 1

groups:
  - name: SILA Alerts
    interval: 1m
    rules:
      # Alerta para alta taxa de erro de validação de CPF
      - alert: HighCPFValidationErrorRate
        expr: rate(sila_cpf_validation_errors_total[5m]) / rate(sila_cpf_validation_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Alta taxa de erro na validação de CPF"
          description: "A taxa de erro na validação de CPF está em {{ $value | humanizePercentage }} (acima de 5%)"

      # Alerta para baixa taxa de acerto do cache de CPF
      - alert: LowCPFCacheHitRate
        expr: (1 - (rate(sila_cpf_validation_cache_misses[5m]) / rate(sila_cpf_validation_total[5m]))) * 100 < 70
        for: 15m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Baixa taxa de acerto no cache de CPF"
          description: "A taxa de acerto do cache de CPF está em {{ $value | humanizePercentage }} (abaixo de 70%)"

      # Alerta para tempo de resposta elevado
      - alert: HighCPFValidationLatency
        expr: histogram_quantile(0.95, sum(rate(sila_cpf_validation_duration_seconds_bucket[5m])) by (le)) > 0.5
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Alto tempo de resposta na validação de CPF"
          description: "O tempo de resposta P95 para validação de CPF está em {{ $value | humanizeDuration }} (acima de 500ms)"

      # Alerta para cache quase cheio
      - alert: CPFCacheAlmostFull
        expr: sila_cpf_validation_cache_size > 900
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Cache de CPF quase cheio"
          description: "O cache de CPF está com {{ $value }} itens (acima de 900)"

      # Alerta para falha na coleta de métricas
      - alert: MetricsCollectionFailed
        expr: up{job="sila-backend"} == 0
        for: 1m
        labels:
          severity: critical
          team: infra
        annotations:
          summary: "Falha na coleta de métricas do backend"
          description: "O endpoint de métricas do backend não está respondendo"

